# Generated by Django 2.1.3 on 2018-11-17 10:07

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body2',
            field=markdownx.models.MarkdownxField(default=''),
        ),
    ]
